name: lint

on: [push, pull_request]

env:
  WESNOTH_VERSION: 1.16.10

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Verify images
      uses: czyzby/wesnoth-png-optimizer@v1
      if: always()
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        threshold: 50
