---
name: Map Diff

on:
  pull_request_target:
    paths:
      - '**.map'

jobs:
  comment-map-diff:
    permissions:
      pull-requests: write
    continue-on-error: true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Package install with npm
        run: cd utils/wesnoth-map-diff && pwd && (npm install || stat package.json)
      - name: Package build with npm
        run: cd utils/wesnoth-map-diff && npm run build:prod
      - name: Get maps diff
        id: get-maps-diff
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          sudo apt-get -y -q install pngquant
          comment_body=""
          log() { printf '\e[1m%s\e[m\n' "$*"; } # write log message in bold

          sync && log "in $(pwd): getting changed maps with SHA of ${SHA}"
          git fetch origin
          git checkout "$SHA"
          cd utils/wesnoth-map-diff
          sync && log "now in $(pwd), which ought to report being a submoduleâ€¦"
          git status
          git fsck
          git fetch
          if test -x "$(which mapfile)"; then \
            sync && log "mapfile is '$(which mapfile)'"; \
          elif test -n "$(type mapfile 2>/dev/null)"; then \
            sync && log "about mapfile: '$(type mapfile)'"; \
          else \
            ls -al; \
          fi
          mapfile -t map_paths < <(pushd ../.. && git diff --name-only HEAD "$SHA" | grep '\.map$' && popd)

          sync && log "Looping through map_paths next..."
          for map_path in "${map_paths[@]}"
          do
            ## Get new map version
            log "Check out $map_path from $SHA..."
            new_map=${map_path##*/}
            git show "$SHA":"$map_path" > "$new_map"

            log "Generate map diff image for $map_path..."
            node build/index.js "../../$map_path" "$new_map" diff_image.png
            identify diff_image.png

            log 'Compress image...'
            pngquant --force --output diff_image.png diff_image.png
            identify diff_image.png

            log 'Uploading diff_image.png...'
            json=$(curl -s -F image=@diff_image.png https://api.imgur.com/3/upload | tee /dev/stderr) \
              || continue

            log 'Generating HTML comment...'
            html=$(jq -r --arg path "$map_path" 'if .data.link != null
              then @html "<h3>\($path)</h3><img src=\"\(.data.link)\" /> <br />"
              elif has("errors") then .errors[].status | halt_error
              else "Unexpected JSON structure!\n" | halt_error end' <<< "$json") \
                || continue
            comment_body+=$html
          done

          if test -z "${comment_body}"; then
            comment_body="ERR: map diff action failed to output valid comment!"
          fi

          printf 'COMMENT_BODY=%s\n' "$comment_body" >> "$GITHUB_OUTPUT"
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.get-maps-diff.outputs.COMMENT_BODY }}
